dist: trusty
language: rust
cache:
    cargo: true
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: stable
    - rust: beta

script:
    - rustc --version
    - cargo build
    - cargo test
    - cargo test --release
    - cargo bench

