[package]
name = "white-balance"
description = "Rust implementation of white balance methods"
version = "0.1.0"
authors = ["Thijs Vermeir <thijsvermeir@gmail.com>"]

[dependencies]
num-traits = "0.1.32"
image = "*"
clap = "*"
nalgebra = "0.10.*"
num = "*"
rand = "*"

